### ISSUE TITLE
[BUG] error during build process

### ISSUE THREAD

**Issue by mdusza** [priteshrnandgaonkar/react-native-call-detection#11]
Hello,

I receive following errors when trying to run the app after linking the library:

[...]\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppe
arance.Material.Widget.Button.Borderless.Colored'.

[...]\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppe
arance.Material.Widget.Button.Colored'.

[...]\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextApp
earance.Material.Widget.Button.Borderless.Colored'.

[...]\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextApp
earance.Material.Widget.Button.Colored'.

More info: 
"react-native": "0.48.3",
"react-native-call-detection": "^1.6.1",

from build.gradle:
 compileSdkVersion 23
 buildToolsVersion '23.0.1'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
    }

I would appreciate any suggestions, thanks

**Comment by DragonRaider5** [comment]
Hi,

Thanks for the report. How did you link react-native-call-detection?
I currently don't know how this issue could be related to RNCD, would it be possible for you to share a Repo reproducing this error?

**Comment by mdusza** [comment]
@DragonRaider5 

I used `react-native link` command and verified manually that it has linked correctly, according to the readme.
Unfortunately I can't share the repo I'm working on right now, but I'll try to setup a clean app and recreate the problem.

**Comment by DragonRaider5** [comment]
Thanks, I'm looking forward to the test project - I'll try my best to solve the issue if it's reproducible that way.

**Comment by mdusza** [comment]
@DragonRaider5 

[Here](https://github.com/mdusza/rncd-bug) is the repo which experiences the same error.
What I did is creating the new app using `react-native init`, added and linked rncd.

**Comment by priteshrnandgaonkar** [comment]
I will release a new version in npm once the PR for this fix is raised and merged. 😉

**Comment by priteshrnandgaonkar** [comment]
Released 1.6.2
