### ISSUE TITLE
I want to receive Disconnected event when I call someone

### ISSUE THREAD

**Issue by jihokim2** [priteshrnandgaonkar/react-native-call-detection#16]
Hello. I develop app using this library. 
But I found one problem
When I call someone, I can not receive disconnect event. Just I receive event when someone call me.
Are you add this event or fix this event? Thank you

**Comment by DragonRaider5** [comment]
Hi,

Thanks for reporting this issue.

On which platform does this problem occur?
Could you maybe setup a small repo showcasing the issue?

jihokim2 <notifications@github.com> schrieb am Mo., 5. März 2018, 10:16:

**Comment by jihokim2** [comment]
I see this issue occurs every time in android(I didn't see IOS). So I think when you know this problem, you can fix it easily. 
here is simple example.

let callDetector;
componentDidMount() {
        callDetector = new CallDetectorManager((event)=> {
            if (event === 'Disconnected') {
                // Do something call got disconnected
                this.setState({modalVisible: true, selectStarCount: 5});
            }
        })
}
componentWillUnmount() {
            callDetector.dispose();
}

**Comment by DragonRaider5** [comment]
Hi,

Could you please check wether you receive a `Missed` event instead? I currently can’t try it out myself ;)

**Comment by jihokim2** [comment]
No I can not receive any event. After I modify manager java file I can receive what I want. If you have time, please fix it.

**Comment by DragonRaider5** [comment]
If you've already fixed it, could you maybe open a PR with the fix or just send it here? I should not try to fix it again if you've already done so 👍

**Comment by jihokim2** [comment]
I will send here the code tommorrow. Thank you

**Comment by arrygoo** [comment]
@jihokim2 @DragonRaider5 I'm having the exact same issue on Android. Once the phone call starts it emits a `Offhook` event, but after that I don't get any events emitted when the phone call is disconnected. Looking forward to seeing your PR!

**Comment by jihokim2** [comment]
[CallDetectionManagerModule.java.zip](https://github.com/priteshrnandgaonkar/react-native-call-detection/files/1783212/CallDetectionManagerModule.java.zip)

I modify file and explain what I think. Please modify this file using this.

**Comment by arrygoo** [comment]
@jihokim2 Hey that solution worked for me! 
Also I found this fork: https://github.com/soledaddiez/react-native-call-detection
Which does not have the said issue for me. Might be worth giving a try?

**Comment by DragonRaider5** [comment]
Hey,

Thanks for your help - I'll commit this fix to the codebase tomorrow.

@priteshrnandgaonkar can you push the new release to npm afterwards? Thanks in advance.

**Comment by DragonRaider5** [comment]
Fixed the bug in PR #19 - please excuse the delay, I was very busy with private projects 😞 

@priteshrnandgaonkar ready for NPM ;D

For the meantime (until the new version is on NPM) you can install this package directly from GitHub using `npm i --save git+https://github.com/priteshrnandgaonkar/react-native-call-detection.git`
