### ISSUE TITLE
"Disconnect" event when switching back to app while phone call still in progress

### ISSUE THREAD

**Issue by hchac** [priteshrnandgaonkar/react-native-call-detection#17]
Hello,

I am having an issue on Android relating to getting a "Disconnect" event when I switch back to my app, while a phone call is still in progress.

Specifically, [this line](https://github.com/priteshrnandgaonkar/react-native-call-detection/blob/e63c3304558d4214aa7370f85497f1345fb54034/android/src/main/java/com/pritesh/calldetection/CallDetectionManagerModule.java#L88) in the if statement.

Steps to reproduce:

1) Run your app and set up handler with CallDetectionManager
2) Receive a phone call and answer
3) Switch back to your app without hanging up the phone call
4) Disconnect event occurs, even though phone call is still in progress

Is this intentional, or a leftover artifact? Ideally I would only receive a "Disconnect" when the phone call has ended, or am I misinterpreting this event?

Thanks.

**Comment by DragonRaider5** [comment]
Hey,

If I'm remembering everything correctly, apps running in the background don't properly receive call state events (on android) - that's why we reset the current state and emit a 'Disconnected' event, assuming that he call has ended in the due time.

**Comment by hchac** [comment]
Hey DragonRaider5,

I see, so the assumption is that if the app using react-native-call-detection comes back to the foreground, then the call must have ended?

And if that's not the case (the call is still in progress), then unfortunately it will still receive a "Disconnect" event, because Android is not sending call state events to app's running in the background so this is the only workaround that is feasible at the moment?

**Comment by DragonRaider5** [comment]
Yes, the second paragraph is right. We don't know wether or not the call has ended yet and that's why we assume it did in order to not mess up the next events and to prevent apps using our library from "thinking" that the call never ended - even if it actually did while the app was in background.

**Comment by code-johnny-code** [comment]
@DragonRaider5 What is the purpose of the `onActivityResumed` method?
https://github.com/priteshrnandgaonkar/react-native-call-detection/blob/fd409c6c65bd03937f9c3c03b984d1c62fe2b0c4/android/src/main/java/com/pritesh/calldetection/CallDetectionManagerModule.java#L84-L90

 I have been doing some testing and find that if I remove lines 86-89 the call state events fire appropriately even with the Android app in the background.

Essentially, it seems that if we stop trying to handle the call state manually when the app resumes, it works just fine. I wanted to check and see what I'm missing before submitting a PR for this.

**Comment by DragonRaider5** [comment]
Hi @code-johnny-code ,

have you tried out what happens when the call disconnects while the app is in background? Based on our findings (and the way RN was supposed to work on Android), no events are processed when the app is closed. This is why we just assume the call has disconnected as the app gets into foreground again.

Let me know what you experienced, thanks for your contribution! :)

Maybe sth changed with RN/Android version or the behavior differs based on devices - albeit I highly doubt it.
