### ISSUE TITLE
How to get incoming number ?

### ISSUE THREAD

**Issue by sumit-khajanchi** [priteshrnandgaonkar/react-native-call-detection#2]
Hi There,

I just want to know that is there any method or something through which I can get the incoming number.

Thanks

**Comment by priteshrnandgaonkar** [comment]
Unfortunately, there is no method for getting an incoming number. May be you can raise a PR. Or I will integrate it once I get time.

**Comment by nezriffic** [comment]
Would be perfect to have a method to reject the incoming call as well :)

**Comment by DragonRaider5** [comment]
Hey guys,
I'm on it. Hoping to submit a PR soon. I've already identified the problem on android, it was about permissions not beeing granted properly.

**Comment by DragonRaider5** [comment]
Hi,
what about my PR? :)

**Comment by priteshrnandgaonkar** [comment]
Hi,
Currently travelling, will look into it once I am back? Thanks for PR

**Comment by DragonRaider5** [comment]
Sounds good to me - you're welcome 😄 have a good time!

**Comment by DragonRaider5** [comment]
Hey,
how is it going? Did you have some spare time yet? ;)

**Comment by priteshrnandgaonkar** [comment]
Hi,
This weekend, will see. Have been very busy. Sorry for the delay

**Comment by priteshrnandgaonkar** [comment]
Closing it as this feature is added in #3

**Comment by rockyhuber** [comment]
Hi,
What about rejecting a phone call? I second that notion for it being a great feature.

**Comment by Udbhav12** [comment]
Hi

Is it possible to get incoming number in iOS?

**Comment by muzamilijaz** [comment]
Hi ,
It is possible to reject/block a call using this library ? A great feature , will be appreciated

**Comment by nguyenvanphuc2203** [comment]
Is it possible to get incoming number in iOS?
