### ISSUE TITLE
Feature Request: add "Dialing" support for Android

### ISSUE THREAD

**Issue by csepulv** [priteshrnandgaonkar/react-native-call-detection#20]
While the Android TelephonyManager doesn't support outgoing/dialing directly, would it be possible to map "Dialing" to the a [BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver) and use the  [ACTION_NEW_OUTGOING_CALL](https://developer.android.com/reference/android/content/Intent#ACTION_NEW_OUTGOING_CALL) intent?

**Comment by DragonRaider5** [comment]
Could this "technique" also be used to address #17?

**Comment by csepulv** [comment]
Probably. I wound up skipping React Native and writing native iOS (CallKit) and Android apps. For Android, I found these very helpful:
http://www.theappguruz.com/blog/detecting-incoming-phone-calls-in-android
https://gist.github.com/ftvs/e61ccb039f511eb288ee
