### ISSUE TITLE
Crash: Attempt to invoke virtual method 'void android.telephony.TelephonyManager.listen(android.telephony.PhoneStateListener, int)' on a null object reference com.pritesh.calldetection.CallDetectionManagerModule.stopListener

### ISSUE THREAD

**Issue by konstantin-mohin** [priteshrnandgaonkar/react-native-call-detection#21]
Hi,

sometimes a mysterious crash happens  on android devices, 
there is no scenario to reproduce it,

mb we should add an additional `if statement ` to prevent this crash ?

**Comment by DragonRaider5** [comment]
Hi,

thanks for reporting this issue. Adding an `if` to prevent this from happening seems valid - although I'd like to find the source of this problem, as it was never reported before (and this `if` might be a solid yet bad way around if we don't understand what really happens and than occasionally brick the call detection).

On which Android version does this problem occur? Maybe it is related to an API change? Also, would it be possible for you to fork this repository, add the `if statement` and try it out for some time so we at least can be some kind of sure, that it doesn't brick?

Thanks in advance,
DragonRaider5

**Comment by konstantin-mohin** [comment]
@DragonRaider5 hi, 

> and this if might be a solid yet bad way around if we don't understand what really happens

yeah just thought to add this as a workaround

> On which Android version does this problem occur? 

it was LG G5 on Android 6.0.1

> Maybe it is related to an API change?

I think that this is just related to API changes

> would it be possible for you to fork this repository, add the if statement

need to learn Java =)

**Comment by DragonRaider5** [comment]
For a short term fix we could add the `if statement` mentioned above. However I'm not sure about how this is going to impact the reliability of the module.

**Comment by konstantin-mohin** [comment]
@jacobbeasley 

no, it is not.

it is difficult to reproduce the crash, I've changed my code since I think it's related to API... 

I'll update you if it helps.

**Comment by jacobbeasley** [comment]
I'll dig through the Java code today and see if I can recognize any way that this might be happening. I agree that it's important to understand the root cause of the issue.

**Comment by DragonRaider5** [comment]
I think I might have tracked it down (maybe, just guessing) - as the error indicates, it crashes at `stopListener` in [CallDetectionManagerModule.java](https://github.com/priteshrnandgaonkar/react-native-call-detection/blob/master/android/src/main/java/com/pritesh/calldetection/CallDetectionManagerModule.java) at line 53.
This could mean, that you call `callDetector.dispose()` after the user previously denied phone state access, resulting in `callDetectionPhoneStateListener` beeing `null`.

Try the following: call `callDetector.dispose()` **twice** directly after creating the `new CallDetectorManager()` from `react-native-call-detection` and look at the error you're receiving.
Does it match the one in production?

**Comment by DragonRaider5** [comment]
Anybody willing to test it?

**Comment by jacobbeasley** [comment]
I want to see if I can replicate the "glitch" (based on your recommendation) first, but yeah I'll do some testing later today.

**Comment by DragonRaider5** [comment]
So, could you replicate it?

**Comment by jacobbeasley** [comment]
I'll test to see if I can replicate it consistently later today... Then
I'll implement your suggested fix and see if it works.

**Comment by jacobbeasley** [comment]
Okay, so I personally couldn't replicate it in the wild, but when I called dispose() twice, it did replicate the crash. So, as you suggested, I bet it happens when the app isn't given permission OR if there is a race condition between permission being granted and dispose() being called. 

Instead of adding a null check, another approach might be to track app state. So, in startListener() you could have a boolean you set called listening. 

    this.listening = true

Then it stopListener() you could check whether listening is true or not. 

   if (this.listening) // stop listener

Or a null check would suffice, since the absence of a value indicates they aren't listening. If you wanted to get real fancy you could wrap it in AtomicReference so its thread-safe.

**Comment by jacobbeasley** [comment]
Dumb question - so, my app never really unsubscribes from the call detector except for when the app closes. Could I just comment out the call to dispose() to avoid this issue?

**Comment by jacobbeasley** [comment]
By the way, I just wanted to comment on how useful a project this is. Thanks for all of your work putting it together!

**Comment by DragonRaider5** [comment]
Hm... For some reason I have to write "sorry for for the late response" quiet a lot today...

However: Not calling `dispose` at all won't really fix your issue and will result in your app not properly cleaning up.

Instead I'd recommend to track wether or not you're granted the permission and only call `dispose` if you've been granted permission.

This could be done in this manner:

```js
import React from 'react'

import CallDetectorManager from 'react-native-call-detection'
import App from './app.js'

export default class extends React.PureComponent {
  constructor (props) {
    super(props)
    this.permissionGranted = true
  }

  componentDidMount () {
    this.callDetector = new CallDetectorManager(this.handleCallEvent, false /* we don't want to read the incomming phone number */, this.onDeniePermission)
  }

  handleCallEvent (event) {
    console.log(event)
  }

  onDeniePermission () {
    this.permissionGranted = false
  }

  componentWillUnmount () {
    if (this.permissionGranted && this.callDetector) {
      this.callDetector.dispose()
    }
  }

  render () {
    return <App />
  }
}
```

However you're right about the race condition... To prevent this, we'd also need to fire the callback when permission is granted, so you could set `permissionGranted` to `false` as a default, resulting in the code not trying to call `dispose` when the user hasn't done any permission decision.

**Comment by manjeets12** [comment]
is that fixed?

**Comment by roysG** [comment]
Any update?

**Comment by AftabUfaq** [comment]
why this is closed. there is still issue in this library.

**Comment by akimabs** [comment]
any update ?
