### ISSUE TITLE
Disconnected state while bringing application to foreground eventhough call in progress

### ISSUE THREAD

**Issue by basheerkohli** [priteshrnandgaonkar/react-native-call-detection#23]
Hi Pritesh,

How can i handle the call end state the problem is here because of   when am returning to my application when the call is intact callback state is then disconnected eventhough my call is going in background .I figured it this happens because of this code right.So can u please let me know why u have written this.

    @Override
    public void onActivityResumed(Activity activity) {
        if (wasAppInOffHook && jsModule != null) {
            wasAppInOffHook = false;
            jsModule.callStateUpdated("Disconnected", null);
        }
    }

**Comment by DragonRaider5** [comment]
See #17
