### ISSUE TITLE
build error for junit

### ISSUE THREAD

**Issue by top-master** [priteshrnandgaonkar/react-native-call-detection#25]
please add below to `build.gradle` so I no longer need to do that manually:
`testCompile "junit:junit:4.12"`

**Comment by sidferreira** [comment]
I just had this issue...

**Comment by DragonRaider5** [comment]
@top-master @sidferreira thanks for the catch, do I have to put it into root or "android"? Sorry, I'm not into android development atm.

**Comment by ddeschenes-logmein** [comment]
What is the solution for that ? I have the same issue. Where to put `testCompile` ?

**Comment by ddeschenes-logmein** [comment]
Finally got it right. Into the main `build.gradle` file, under `android` package, add this to global config:
```
subprojects {
    afterEvaluate {project ->
        dependencies {
            testCompile group: 'junit', name: 'junit', version: '4.+'
        }  
    }
}
```

**Comment by DragonRaider5** [comment]
See #84.
