### ISSUE TITLE
question: does the detection works when the app is in background or closed?

### ISSUE THREAD

**Issue by emranio** [priteshrnandgaonkar/react-native-call-detection#27]
I want to detect the call state and run some js code even if the app is closed or in background mode. any help or information regarding achieving that?

thanks, it's a very useful package :) #

**Comment by DragonRaider5** [comment]
Hey,

sadly I'm not sure whether or not this is possible using `react-native` at all. If it is, I'm not capable of helping you to achieve it.

Happy that the package helps you 👍

**Comment by bkkwok** [comment]
If its possible with an ios or android shouldn't it be possible with react-native by using/creating a native module?

**Comment by priteshrnandgaonkar** [comment]
I think its not possible in iOS. For iOS once the app is terminated you can't detect anything. Whereas in  background mode for iOS you can do stuff, but the background mode may exist for a brief time and its generally meant for finishing off any undone work. Not sure about android though.

**Comment by DragonRaider5** [comment]
See #64 for an android solution.
