### ISSUE TITLE
Invariant violation: Native module cannot be null

### ISSUE THREAD

**Issue by knalliyappan** [priteshrnandgaonkar/react-native-call-detection#32]
While use the react-native-call-detection with existing project (Project contain the pod file) got the "Invariant violation: Native module cannot be null" in iOS platform.
=> Without pod file working file.
![Call_Detection](https://user-images.githubusercontent.com/48433441/54111309-95323200-4409-11e9-8b24-e8f29fe54a68.png)

Versions:
 "react": "16.4.1",
 "react-native": "0.56.0",
 "react-native-call-detection": "^1.6.4",

Attached the screen for reference:

**Comment by joetannenbaum** [comment]
@knalliyappan I don't know if you're still using this library or solved this issue, but I came across the same error and realized that I had never run `pod install` after the `react-native link` step. Fixed the issue for me.
