### ISSUE TITLE
How manage calls on my app

### ISSUE THREAD

**Issue by ayozebarrera** [priteshrnandgaonkar/react-native-call-detection#33]
Hi guys.. noob question, for android:

When I receive a call, **even with my app as default phone app**, it switch to the Phone call of Android. How can I achieve that my app doesn't switch to another app, so I can do whatever I want when a call is incoming?

I tried to create an own InCallService class empty but when I receive a call, my app crashes

Thanks for the help!

**Comment by DragonRaider5** [comment]
Hey,

I think we are not the right people to help you here. Please try asking your questions on Stackoverflow, there's a higher chance that you get a good answer there.
