### ISSUE TITLE
Bridge is flasky on iOS

### ISSUE THREAD

**Issue by julioxavierr** [priteshrnandgaonkar/react-native-call-detection#36]
I set up the CallDetector in `componentDidMount` on one of my screens, pretty much in the same way that it was set on the example:

https://github.com/priteshrnandgaonkar/react-native-call-detection/blob/7c47b4d2c3510377e890e7b825f8c59c1f42dfc8/CallDetectionExample/src/HomeComponent.js#L29

However, from time to time I receive the following error (it doesn't happens every time, but frequently) after ending a call:

```
bridge is not set. 
This is probably because you've explicitly synthesized the bridge in RCTCallDetection, 
even though it's inherited from RCTEventEmitter.
```

Could this be related to memory leak? Has anyone had this problem?

**Comment by soledaddiez** [comment]
We are getting the same issue
```Bridge is not set. This is probably because you've explicitly synthesized the bridge in CallDetectionManager, even though it's inherited from RCTEventEmitter.'
```

**Comment by julioxavierr** [comment]
@soledaddiez I'm using this repo for now:
https://github.com/liamse/react-native-call-observer
But it's only implemented for iOS. Hope it solves your problem in the meanwhile.

**Comment by dowatugkins** [comment]
@julioxavierr @soledaddiez If you could pull my branch and test to see if it fixes your issue, that would be great. We also ran into this issue, and noticing that this repo uses the deprecated API CallTelephony I updated the iOS side to use the new CallKit API instead. So far I haven't seen any crashes and get the same events as expected when expected.

**Comment by julioxavierr** [comment]
Will do it and let you know, thanks for helping @dowatugkins

**Comment by priteshrnandgaonkar** [comment]
Closing it as its a stale issue
