### ISSUE TITLE
Error on android build

### ISSUE THREAD

**Issue by AFMW** [priteshrnandgaonkar/react-native-call-detection#4]
When i try to run the 'react-native run-android' command  it shows the following error:

> :react-native-call-detection:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
> /Users/duvanvargas/Documents/proyectos/EpoConstructoras/Android/PruebaPush/node_modules/react-native-call-detection/android/src/main/java/com/pritesh/calldetection/CallDetectionManager.java:35: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> 1 error
> :react-native-call-detection:compileReleaseJavaWithJavac FAILED
> FAILURE: Build failed with an exception.

>* What went wrong:
>Execution failed for task ':react-native-call-detection:compileReleaseJavaWithJavac'.

my RN version is:  "react-native": "0.48.2" and the installed one of the 'react-native-call-detection' is: "react-native-call-detection": "^1.4.1"

**Comment by DragonRaider5** [comment]
Go into node_modules/react-native-call-detection/android/src/main/java/com/pritesh/calldetection/CallDetectionManager.java and remove the function (and the `@override`) starting at line 35. It turned deprecated (as it never rly was used) in one of the latest RN versions (I think it was 0.48 actually).

**Comment by priteshrnandgaonkar** [comment]
Removed `@override`

**Comment by priteshrnandgaonkar** [comment]
Check version `1.5.0`
