### ISSUE TITLE
Android Issue: Violation of Permissions policy

### ISSUE THREAD

**Issue by costel21d** [priteshrnandgaonkar/react-native-call-detection#47]
I have this issue, the app can not be approved in Google Play Store because I use READ_CALL_LOG permission and in declaration form I don't know what should I choose.

I use only phone number for incoming and outgoing calls to suggest client records that are already from our app db.

https://i.redd.it/se0p9gcukm521.png

Can anybody help me?

**Comment by SnehalAgrawal** [comment]
Can you please have a look at [this](https://stackoverflow.com/a/55394807)?  The suggestion from this guy can help you.

**Comment by DragonRaider5** [comment]
@costel21d sorry for the late answer, but the question in your image suggests that all of the use-cases are not allowed. Did you solve your issue in the meantime?
