### ISSUE TITLE
Doesn't work in Release Mode or if there is Truecaller installed

### ISSUE THREAD

**Issue by kailashvele** [priteshrnandgaonkar/react-native-call-detection#49]
It works fine on the Debug mode but doesn't work in the release mode.

Also if there is Truecaller it doesn't work.

When I say it doesn't work what I mean by that is Call End event is not fired for the above two scenarios.

**Comment by SnehalAgrawal** [comment]
There is a long explanation for that. I suggest going through the link suggested below.
https://www.reddit.com/r/androiddev/comments/anc3xa/im_frustrated_from_google_read_call_log_permission/

**Comment by priteshrnandgaonkar** [comment]
Closing the issue, reopen it if the above thread doesn't answer the question
