### ISSUE TITLE
Help avoid installation hardship - please release the newest version of this code and update the docs 🙏

### ISSUE THREAD

**Issue by Rnorback** [priteshrnandgaonkar/react-native-call-detection#58]
Hi 👋,

Just wanted to make a small request to create a tag or release the newest version of this code on `master`.

I went on a wild goose chase because I downloaded this package through yarn and it doesn't have the most recent changes on master.

Master uses `CXCallObserver` which is the up-to-date way to detect calls on iOS.

Or can we just add to run this yarn command in the Readme?
`yarn add https://github.com/priteshrnandgaonkar/react-native-call-detection\#master`

Either way, thanks for the package, it saves me the trouble of maintaining a couple of native modules myself 🙏. 

Cheers!

**Comment by Rnorback** [comment]
Also, adding the step to run `pod install` would be helpful as well.

**Comment by DragonRaider5** [comment]
@Rnorback do you think you could provide a PR for the second request?

@priteshrnandgaonkar what do you think about a new release on npm?

**Comment by priteshrnandgaonkar** [comment]
Made an npm release
