### ISSUE TITLE
i get always permission denied

### ISSUE THREAD

**Issue by roysG** [priteshrnandgaonkar/react-native-call-detection#60]
What permissions do i nee to ask?

**Comment by ihabkhaled** [comment]
is there any solution for this ?

**Comment by DragonRaider5** [comment]
You can use `requestPermissionsAndroid()`. See `src/index.js` for its call signature.
Did this solve your issue?

**Comment by DragonRaider5** [comment]
Closing because of no feedback. Will be reopened in case we get a response.

**Comment by myckhel** [comment]
To get incoming Phone Number
You need to ask for this permission `READ_CALL_LOG`

as stated in the android sdk doc https://developer.android.com/reference/android/telephony/PhoneStateListener#onCallStateChanged(int,%20java.lang.String)
