### ISSUE TITLE
v1.8.2 Android auto linking not working with RN 61.5

### ISSUE THREAD

**Issue by dcenatiempo** [priteshrnandgaonkar/react-native-call-detection#62]
V 1.8.2 doesn't seem to be working correctly on RN 61.5. It builds fine with no errors/crashes, but the listener is never triggered.

I am not sure if I have everything installed correctly. I am very confused because on here https://www.npmjs.com/package/react-native-call-detection the install instructions say to edit the `MainApplication.java`, `settings.gradle` and `build.gradle` files, but on github, it says `Autolinking should work without manual changes`. Also, the example app seems like it needs to be updated to use autolinking.

The reason I think it is not working is because I am putting a debugger just inside the listener and it is never triggered. Here is the file I am using this in:

```
import { useState, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import CallDetectorManager from 'react-native-call-detection';
import { DialerActionsConst } from 'reducers/dialer';

export default function CallDetectionSetup() {
  const dispatch = useDispatch();

  const [callDetector, setCallDetector] = useState();

  useEffect(() => {
    setupCallDetector();

    return () => {
      if (callDetector) {
        callDetector.dispose();
      }
    };
  }, []);

  function setupCallDetector() {
    debugger // this is being tripped
    setCallDetector(new CallDetectorManager((event) => {
      debugger // this is never being tripped
      switch (event) {
        case 'Offhook':
          dispatch({ type: DialerActionsConst.CALL_CONNECTED });
          break;
        case 'Connected':
          dispatch({ type: DialerActionsConst.CALL_CONNECTED });
          break;
        case 'Dialing':
          dispatch({ type: DialerActionsConst.CALL_CONNECTED });
          break;
        case 'Disconnected':
          dispatch({ type: DialerActionsConst.CALL_DISCONNECTED });
          break;
        default:
          break;
      }
    }));
  }

  return null;
}
```

**Comment by dcenatiempo** [comment]
Actually, It was building because I was not autolinking in the react-native.config:
```
'react-native-call-detection': {
       platforms: {
         android: null,
       },
     },
```
when I remove this, I get an error in the build: 
```
Error: Command failed: ./gradlew app:installFlavorDebug -PreactNativeDevServerPort=8081
/pathToApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:118: error: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types;
      new CallDetectionManager(),
required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

**Comment by dcenatiempo** [comment]
OK, I changed the title of this issue. I was able to get the package to work, but it required manual linking. The documentation says that autolinking should work, but i could not get it to work in my setup.

**Comment by talha-ahmed** [comment]
Yes I believe the fix for that is not published to npm. If you use 
"react-native-call-detection": "github:priteshrnandgaonkar/react-native-call-detection.git#d6e90c32188341b36508853eb743b9a475acdd5a",

in your package.json then it works

**Comment by talha-ahmed** [comment]
I did leave a comment here 
https://github.com/priteshrnandgaonkar/react-native-call-detection/commit/d6e90c32188341b36508853eb743b9a475acdd5a#comments

**Comment by priteshrnandgaonkar** [comment]
Apologies for delay. I have made a release. Closing the issue, feel free to reopen it, if the problem still persists.

**Comment by McDreamy** [comment]
event listener is not trigger when a phone call is made.
