### ISSUE TITLE
Background working on Android?

### ISSUE THREAD

**Issue by renege** [priteshrnandgaonkar/react-native-call-detection#64]
Hello,
I got it to work, but it only works when the App is in the Foreground.
How can I make it to work that the App will open when there is a Call detected on an Android device?

**Comment by syllasrangel** [comment]
The [react-native-foreground-service](https://github.com/voximplant/react-native-foreground-service) solved my problem. With react-native-foreground-service the application remains running as if it were in the foreground, even when the user closes the app (a notification is displayed to inform that the app is still running). To do this, simply starts both the call detector listener and the foreground service on componentDidMount and do not close them with componentWillUnmount. Hope this solves your problem.

**Comment by renege** [comment]
@syllasrangel great, but i have to support android 7. then it is not a solution. right?

**Comment by syllasrangel** [comment]
> @syllasrangel great, but i have to support android 7. then it is not a solution. right?

Actually, the react native foreground service supports Android 7 as well. Indeed, the demo provided by the module requires minimum SDK version 19 (Android 4.4).

**Comment by SokolovRU** [comment]
Hi! Apparently I'm doing something wrong, but I can't listen to calls in the background. How is this supposed to work? If necessary, I can attach the project code.

**Comment by SokolovRU** [comment]
@renege
