### ISSUE TITLE
Phone Number missing

### ISSUE THREAD

**Issue by nmaddock** [priteshrnandgaonkar/react-native-call-detection#65]
I can't seem to capture the outgoing number, all th events are capturing fine.

this.callDetector = new CallDetectorManager((event, phoneNumber)=> {

      alert(event);
      alert(phoneNumber);

phoneNumber is undefined

is it possible to capture the number your calling in iOS?

**Comment by DragonRaider5** [comment]
Sadly it isn't AFAIK (due to privacy concerns, at least the last time I checked). Correct me if I'm wrong, providing a source. In that case we might be able to add it to our library :)
