### ISSUE TITLE
Phone number is empty

### ISSUE THREAD

**Issue by patryq955** [priteshrnandgaonkar/react-native-call-detection#76]
When I have an incoming call on a closed application and start the application. I get the number, but when I have an incoming call and answered a call on the closed application and I open the application and I get an empty string.

**Comment by DragonRaider5** [comment]
Hey @patryq955 ,

can you check whether the mentioned PR fixed it by installing react-native-call-detection from git using `npm install https://github.com/priteshrnandgaonkar/react-native-call-detection.git`?

Thanks in advance.

**Comment by patryq955** [comment]
works great
thanks
