### ISSUE TITLE
NativeModules.CallDetectionManagerAndroid is null

### ISSUE THREAD

**Issue by klishinoleg** [priteshrnandgaonkar/react-native-call-detection#82]
const NativeCallDetector = NativeModules.CallDetectionManager
const NativeCallDetectorAndroid = NativeModules.CallDetectionManagerAndroid

in \node_modules\react-native-call-detection\index.js

Constants is empty. What do i do wrong?

**Comment by maikenunes** [comment]
Hey @klishinoleg!

https://github.com/priteshrnandgaonkar/react-native-call-detection/pull/83
My PR should fix this issue.

Let me know if you need any help.

**Comment by klishinoleg** [comment]
should this work in expo?

**Comment by maikenunes** [comment]
> should this work in expo?

I think so, but I didn't test it there though.

**Comment by DragonRaider5** [comment]
@klishinoleg does Expo support native modules? I think it doesn't, henceforth this module shouldn't work in there as well.

**Comment by klishinoleg** [comment]
I'll try soon, but I think only in bare mode after ejecting.
