### ISSUE TITLE
compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by milon87** [priteshrnandgaonkar/react-native-call-detection#9]
getting this error
Execution failed for task ':react-native-call-detection:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by DragonRaider5** [comment]
Having the actual compiler error would help :D also the RN version and the version of this package you're using might help.

**Comment by milon87** [comment]
can you plz explain a bit.

**Comment by DragonRaider5** [comment]
The error says `see the compiler error output for details`. This means that there was an extended error printed in your console when the build failed. Can you paste it here?

In addition I asked you about the react-native (RN) version you are using and the react-native-call-detection version you are using.
You can look them up in your package.json - it should look somewhat like this:
```json
{
   ...,
   dependencies: {
      ...,
      "react-native": "<VERSION>",
      "react-native-call-detection": "<VERSION>",
      ...
   },
   ...
}
```

I hope this clarified my questions. If it didn't go ahead and ask again ;)

Greets

**Comment by DragonRaider5** [comment]
Hey,
does the problem persist with the newest version of this package?

**Comment by DragonRaider5** [comment]
Closing this issue as the error can't be reproduced and as @milon87 seems to be inactive at the moment.
Feel free to reopen if anybody has additional information!
